version: "3.8"
services:
  rust-backend:
    build: ./backend/Dockerfile
    ports:
      - "8000:8000" # Change the ports as needed
    volumes:
      - ./backend/api:/usr/src/api

  typescript-frontend:
    build: ./frontend/Dockerfile
    ports:
      - "3000:3000" # Change the ports as needed
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
